### PR TITLE
Fix issue #15, #17, #25 and added 6 games

### PR DESCRIPTION
**Pull request by g0ddish**
This should solve issue #15 & #17 , the issue is caused attempting to open a file without specifying FileShare  parameters. Basically, "only open the file if the other guys only opened the file with Read access" is how it currently functions. This commit changes that to "only open the file if the other guys opened it for  Read/Write access" by setting FileShare.ReadWrite.

### CODE REVIEW

**Comment by g0ddish** [comment]
I've added an array of game ids that don't use voice fadeout this should resolve issue #25. The only one in it that I've tested is GO (ID 730). Feel free to launch any supported game and type voice_fadeouttime if it is unknown feel free to add it

**Comment by g0ddish** [comment]
I've also added Gmod and some more options.

**Comment by SilentSys** [comment]
I would like to merge your fix for issue #15 and all the games you've added. However, could you please revert AssemblyInfo.vb, Application.myapp, Application.Designer.vb, and lines 339-369(There is a better way of fixing #25).

**Comment by g0ddish** [comment]
AssemblyInfo.vb: Are we following semantic versioning 2.0.0? 

Application.myapp & Application.Designer.vb: Did this affect the "My" namespace usage? Setting AuthenticationMode to 1 shouldn't have any side effects, no? I changed the authentication mode from Windows to application specific.

 lines 339-369: The only solution for this issue is to not execute "voice_fadeouttime" on games that don't support it. How would you like to go about this?

**Comment by SilentSys** [comment]
> AssemblyInfo.vb: Are we following semantic versioning 2.0.0?
Not really.

>Application.myapp & Application.Designer.vb: Did this affect the "My" namespace usage? Setting AuthenticationMode to 1 shouldn't have any side effects, no? I changed the authentication mode from Windows to application specific.
I would like to keep the history of this project clean, and without unnecessary changes.

>lines 339-369: The only solution for this issue is to not execute "voice_fadeouttime" on games that don't support it. How would you like to go about this?
Creating an exemption list is a messy way to go about this. Exemption should instead be a property of `SourceGame`. Also, setting `sv_use_steam_voice 0; sv_allow_voice_from_file 1` is pointless. Those are server only commands. They are to be set by server hosts. Players will receive an error when they try to execute those commands on a public server.

**Comment by g0ddish** [comment]
Ok I've fixed all these issues

**Comment by g0ddish** [comment]
All better :)

**Comment by SilentSys** [comment]
Very nice, much better. However, you've forgotten to use `SourceGame.VoiceFadeOut` instead of the old `UseSteamVoiceExempt`.

**Comment by g0ddish** [comment]
Whoops

**Comment by g0ddish** [comment]
5f6dccf is what you were talking about right

**Comment by SilentSys** [comment]
Yup. Thank you.

**Pull request merged**
